library(rvest)
library(here)
source(here::here("code/common", "bom_data_download.R"))



print_test(2)

bom_solar_data_download(data_type = 122,station_num=3003,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 122,station_num=23034,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature") 
bom_solar_data_download(data_type = 122,station_num=15590,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 122,station_num=31011,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 122,station_num=91148,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 122,station_num=48027,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 122,station_num=200284,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 122,station_num=14015,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 122,station_num=8315,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 122,station_num=8051,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 122,station_num=12038,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 122,station_num=5007,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 122,station_num=36031,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 122,station_num=86282,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 122,station_num=76031,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 122,station_num=26021,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 122,station_num=39083,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 122,station_num=15135,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 122,station_num=32040,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 122,station_num=72150,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 122,station_num=16001,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 122,station_num=66062,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")



#daily minimum 
bom_solar_data_download(data_type = 123,station_num=3003,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 123,station_num=23034,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 123,station_num=15590,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 123,station_num=31011,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 123,station_num=91148,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 123,station_num=48027,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 123,station_num=200284,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 123,station_num=14015,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 123,station_num=8315,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 123,station_num=8051,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 123,station_num=12038,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 123,station_num=5007,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 123,station_num=36031,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 123,station_num=86282,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 123,station_num=76031,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 123,station_num=26021,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 123,station_num=39083,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 123,station_num=15135,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 123,station_num=32040,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 123,station_num=72150,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 123,station_num=16001,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
bom_solar_data_download(data_type = 123,station_num=66062,p_display_type = "dailyDataFile",dest_folder_path = "data/raw_datasets/BOM_Temperature")
